const WORDS = {
    "abada": "abada",
    "abade": "abade",
    "abafa": "abafa",
    "abala": "abala",
    "abalo": "abalo",
    "abana": "abana",
    "abano": "abano",
    "abate": "abate",
    "abeto": "abeto",
    "abona": "abona",
    "abono": "abono",
    "abram": "abram",
    "abrem": "abrem",
    "abreu": "abreu",
    "abria": "abria",
    "abril": "abril",
    "abrir": "abrir",
    "abriu": "abriu",
    "abusa": "abusa",
    "abuse": "abuse",
    "abuso": "abuso",
    "acaba": "acaba",
    "acabe": "acabe",
    "acabo": "acabo",
    "acaso": "acaso",
    "acata": "acata",
    "acede": "acede",
    "acena": "acena",
    "aceno": "aceno",
    "acesa": "acesa",
    "aceso": "aceso",
    "acham": "acham",
    "achar": "achar",
    "achas": "achas",
    "achei": "achei",
    "achem": "achem",
    "achou": "achou",
    "acima": "acima",
    "acode": "acode",
    "acola": "acol\u00e1",
    "acres": "acres",
    "acusa": "acusa",
    "acuse": "acuse",
    "adega": "adega",
    "adere": "adere",
    "adeus": "adeus",
    "adiar": "adiar",
    "adiou": "adiou",
    "adora": "adora",
    "adoro": "adoro",
    "adota": "adota",
    "adote": "adote",
    "adoca": "ado\u00e7a",
    "adubo": "adubo",
    "advir": "advir",
    "advem": "adv\u00e9m",
    "afaga": "afaga",
    "afago": "afago",
    "afega": "afeg\u00e3",
    "afeta": "afeta",
    "afeto": "afeto",
    "afiar": "afiar",
    "afina": "afina",
    "afoga": "afoga",
    "afora": "afora",
    "agita": "agita",
    "agora": "agora",
    "aguda": "aguda",
    "agudo": "agudo",
    "aguca": "agu\u00e7a",
    "ainda": "ainda",
    "ajuda": "ajuda",
    "ajude": "ajude",
    "ajudo": "ajudo",
    "alada": "alada",
    "alado": "alado",
    "alaga": "alaga",
    "alces": "alces",
    "aldea": "alde\u00e3",
    "alega": "alega",
    "alema": "alem\u00e3",
    "algas": "algas",
    "algoz": "algoz",
    "algum": "algum",
    "alhos": "alhos",
    "aliam": "aliam",
    "aliar": "aliar",
    "aliou": "aliou",
    "alisa": "alisa",
    "alias": "ali\u00e1s",
    "almas": "almas",
    "aloca": "aloca",
    "aloja": "aloja",
    "alpes": "alpes",
    "altar": "altar",
    "altas": "altas",
    "alter": "alter",
    "altos": "altos",
    "aluga": "aluga",
    "aluna": "aluna",
    "aluno": "aluno",
    "alvos": "alvos",
    "alcar": "al\u00e7ar",
    "alcas": "al\u00e7as",
    "alcou": "al\u00e7ou",
    "amada": "amada",
    "amado": "amado",
    "amara": "amara",
    "amava": "amava",
    "ambas": "ambas",
    "ambos": "ambos",
    "amena": "amena",
    "ameno": "ameno",
    "amida": "amida",
    "amido": "amido",
    "amiga": "amiga",
    "amigo": "amigo",
    "amola": "amola",
    "amora": "amora",
    "ampla": "ampla",
    "amplo": "amplo",
    "anais": "anais",
    "ancia": "anci\u00e3",
    "andam": "andam",
    "andar": "andar",
    "andas": "andas",
    "andei": "andei",
    "andes": "andes",
    "andou": "andou",
    "anexa": "anexa",
    "anexo": "anexo",
    "anglo": "anglo",
    "angra": "angra",
    "anima": "anima",
    "anime": "anime",
    "anjos": "anjos",
    "anota": "anota",
    "antas": "antas",
    "antes": "antes",
    "antro": "antro",
    "anual": "anual",
    "anula": "anula",
    "anzol": "anzol",
    "aneis": "an\u00e9is",
    "anoes": "an\u00f5es",
    "aorta": "aorta",
    "apaga": "apaga",
    "apara": "apara",
    "apega": "apega",
    "apego": "apego",
    "apela": "apela",
    "apelo": "apelo",
    "apena": "apena",
    "apita": "apita",
    "apito": "apito",
    "apoia": "apoia",
    "apoie": "apoie",
    "apoio": "apoio",
    "aptas": "aptas",
    "aptos": "aptos",
    "apura": "apura",
    "apuro": "apuro",
    "aquem": "aqu\u00e9m",
    "arado": "arado",
    "arame": "arame",
    "arara": "arara",
    "arcar": "arcar",
    "arcas": "arcas",
    "arcos": "arcos",
    "ardem": "ardem",
    "arder": "arder",
    "ardia": "ardia",
    "ardil": "ardil",
    "ardis": "ardis",
    "ardor": "ardor",
    "areal": "areal",
    "areia": "areia",
    "arena": "arena",
    "armam": "armam",
    "armar": "armar",
    "armas": "armas",
    "armou": "armou",
    "aroma": "aroma",
    "arpao": "arp\u00e3o",
    "arroz": "arroz",
    "artes": "artes",
    "asilo": "asilo",
    "aspas": "aspas",
    "assar": "assar",
    "assim": "assim",
    "astro": "astro",
    "ataca": "ataca",
    "ataco": "ataco",
    "atada": "atada",
    "atado": "atado",
    "atear": "atear",
    "ateia": "ateia",
    "ateou": "ateou",
    "ateus": "ateus",
    "atira": "atira",
    "ativa": "ativa",
    "ativo": "ativo",
    "atica": "ati\u00e7a",
    "atlas": "atlas",
    "atrai": "atrai",
    "atriz": "atriz",
    "atroz": "atroz",
    "atras": "atr\u00e1s",
    "atual": "atual",
    "atuam": "atuam",
    "atuar": "atuar",
    "atuou": "atuou",
    "atura": "atura",
    "audaz": "audaz",
    "aulas": "aulas",
    "autor": "autor",
    "autos": "autos",
    "aveia": "aveia",
    "avela": "avel\u00e3",
    "avisa": "avisa",
    "aviso": "aviso",
    "aviao": "avi\u00e3o",
    "axial": "axial",
    "axila": "axila",
    "azeda": "azeda",
    "azedo": "azedo",
    "azuis": "azuis",
    "acude": "a\u00e7ude",
    "acoes": "a\u00e7\u00f5es",
    "aerea": "a\u00e9rea",
    "aereo": "a\u00e9reo",
    "babar": "babar",
    "babas": "babas",
    "bacia": "bacia",
    "bacon": "bacon",
    "bagas": "bagas",
    "bagre": "bagre",
    "baias": "baias",
    "baila": "baila",
    "baile": "baile",
    "baixa": "baixa",
    "baixo": "baixo",
    "baiao": "bai\u00e3o",
    "balas": "balas",
    "balde": "balde",
    "balsa": "balsa",
    "balao": "bal\u00e3o",
    "bamba": "bamba",
    "bambu": "bambu",
    "banal": "banal",
    "banca": "banca",
    "banco": "banco",
    "banda": "banda",
    "bando": "bando",
    "banha": "banha",
    "banho": "banho",
    "banir": "banir",
    "baque": "baque",
    "barba": "barba",
    "barco": "barco",
    "bardo": "bardo",
    "bares": "bares",
    "barra": "barra",
    "barro": "barro",
    "barao": "bar\u00e3o",
    "barca": "bar\u00e7a",
    "basal": "basal",
    "bases": "bases",
    "basta": "basta",
    "baste": "baste",
    "basto": "basto",
    "batas": "batas",
    "batem": "batem",
    "bater": "bater",
    "bateu": "bateu",
    "batia": "batia",
    "batom": "batom",
    "bazar": "bazar",
    "beata": "beata",
    "beato": "beato",
    "bebem": "bebem",
    "beber": "beber",
    "bebeu": "bebeu",
    "bebia": "bebia",
    "bebes": "beb\u00eas",
    "becos": "becos",
    "beija": "beija",
    "beijo": "beijo",
    "beira": "beira",
    "beico": "bei\u00e7o",
    "belas": "belas",
    "belga": "belga",
    "belos": "belos",
    "benta": "benta",
    "bento": "bento",
    "berra": "berra",
    "berro": "berro",
    "berco": "ber\u00e7o",
    "besta": "besta",
    "bicas": "bicas",
    "bicha": "bicha",
    "bicho": "bicho",
    "bicos": "bicos",
    "bifes": "bifes",
    "bingo": "bingo",
    "bioma": "bioma",
    "birra": "birra",
    "bispo": "bispo",
    "blase": "blas\u00e9",
    "blitz": "blitz",
    "bloco": "bloco",
    "blusa": "blusa",
    "boate": "boate",
    "boato": "boato",
    "bobos": "bobos",
    "bocal": "bocal",
    "bocas": "bocas",
    "bocha": "bocha",
    "bodas": "bodas",
    "bodes": "bodes",
    "bofes": "bofes",
    "boiar": "boiar",
    "boias": "boias",
    "boina": "boina",
    "bolar": "bolar",
    "bolas": "bolas",
    "bolha": "bolha",
    "bolor": "bolor",
    "bolos": "bolos",
    "bolsa": "bolsa",
    "bolso": "bolso",
    "bomba": "bomba",
    "bombo": "bombo",
    "bonde": "bonde",
    "borda": "borda",
    "bordo": "bordo",
    "borra": "borra",
    "bossa": "bossa",
    "bosta": "bosta",
    "botam": "botam",
    "botar": "botar",
    "botas": "botas",
    "botes": "botes",
    "botos": "botos",
    "botou": "botou",
    "botao": "bot\u00e3o",
    "brada": "brada",
    "brado": "brado",
    "brasa": "brasa",
    "brava": "brava",
    "bravo": "bravo",
    "braco": "bra\u00e7o",
    "breca": "breca",
    "brega": "brega",
    "brejo": "brejo",
    "breve": "breve",
    "brida": "brida",
    "briga": "briga",
    "brios": "brios",
    "brisa": "brisa",
    "brita": "brita",
    "broca": "broca",
    "brota": "brota",
    "broto": "broto",
    "broxa": "broxa",
    "bruta": "bruta",
    "bruto": "bruto",
    "bruxa": "bruxa",
    "bruxo": "bruxo",
    "bucal": "bucal",
    "bucha": "bucha",
    "bucho": "bucho",
    "bulas": "bulas",
    "bulbo": "bulbo",
    "bunda": "bunda",
    "buque": "buqu\u00ea",
    "burgo": "burgo",
    "burla": "burla",
    "burra": "burra",
    "burro": "burro",
    "busca": "busca",
    "busco": "busco",
    "busto": "busto",
    "bilis": "b\u00edlis",
    "bocio": "b\u00f3cio",
    "boxer": "b\u00f3xer",
    "bonus": "b\u00f4nus",
    "buzio": "b\u00fazio",
    "cabal": "cabal",
    "cabem": "cabem",
    "caber": "caber",
    "cabia": "cabia",
    "cabos": "cabos",
    "cabra": "cabra",
    "cacau": "cacau",
    "cacho": "cacho",
    "cacos": "cacos",
    "cacto": "cacto",
    "cafes": "caf\u00e9s",
    "caiam": "caiam",
    "caiba": "caiba",
    "caixa": "caixa",
    "calar": "calar",
    "calda": "calda",
    "caldo": "caldo",
    "calha": "calha",
    "calma": "calma",
    "calmo": "calmo",
    "calor": "calor",
    "calos": "calos",
    "calou": "calou",
    "calva": "calva",
    "calvo": "calvo",
    "calca": "cal\u00e7a",
    "calco": "cal\u00e7o",
    "camas": "camas",
    "campa": "campa",
    "campo": "campo",
    "canal": "canal",
    "canas": "canas",
    "canha": "canha",
    "canil": "canil",
    "canis": "canis",
    "canoa": "canoa",
    "canos": "canos",
    "cansa": "cansa",
    "canso": "canso",
    "canta": "canta",
    "cante": "cante",
    "canto": "canto",
    "capas": "capas",
    "capaz": "capaz",
    "capim": "capim",
    "capta": "capta",
    "capuz": "capuz",
    "capao": "cap\u00e3o",
    "caqui": "caqui",
    "caras": "caras",
    "cardo": "cardo",
    "carga": "carga",
    "cargo": "cargo",
    "carne": "carne",
    "caros": "caros",
    "carpa": "carpa",
    "carro": "carro",
    "carta": "carta",
    "casal": "casal",
    "casam": "casam",
    "casar": "casar",
    "casas": "casas",
    "casca": "casca",
    "casco": "casco",
    "casei": "casei",
    "casos": "casos",
    "casou": "casou",
    "caspa": "caspa",
    "cassa": "cassa",
    "casta": "casta",
    "casto": "casto",
    "catar": "catar",
    "cauda": "cauda",
    "caule": "caule",
    "causa": "causa",
    "cause": "cause",
    "cavam": "cavam",
    "cavar": "cavar",
    "cavas": "cavas",
    "cacam": "ca\u00e7am",
    "cacar": "ca\u00e7ar",
    "cacas": "ca\u00e7as",
    "cacao": "ca\u00e7\u00e3o",
    "caida": "ca\u00edda",
    "caido": "ca\u00eddo",
    "cedem": "cedem",
    "ceder": "ceder",
    "cedeu": "cedeu",
    "cedro": "cedro",
    "cegar": "cegar",
    "cegas": "cegas",
    "cegos": "cegos",
    "ceifa": "ceifa",
    "celas": "celas",
    "celta": "celta",
    "cenas": "cenas",
    "censo": "censo",
    "cento": "cento",
    "cepas": "cepas",
    "ceras": "ceras",
    "cerca": "cerca",
    "cerco": "cerco",
    "cerne": "cerne",
    "cerra": "cerra",
    "cerro": "cerro",
    "certa": "certa",
    "certo": "certo",
    "cervo": "cervo",
    "cessa": "cessa",
    "cesta": "cesta",
    "cesto": "cesto",
    "cetim": "cetim",
    "cetro": "cetro",
    "chaga": "chaga",
    "chale": "chal\u00e9",
    "chama": "chama",
    "chame": "chame",
    "chamo": "chamo",
    "chapa": "chapa",
    "chata": "chata",
    "chato": "chato",
    "chave": "chave",
    "checa": "checa",
    "checo": "checo",
    "chefe": "chefe",
    "chega": "chega",
    "chego": "chego",
    "cheia": "cheia",
    "cheio": "cheio",
    "chiar": "chiar",
    "choca": "choca",
    "choco": "choco",
    "chope": "chope",
    "chora": "chora",
    "choro": "choro",
    "chove": "chove",
    "chulo": "chulo",
    "chule": "chul\u00e9",
    "chupa": "chupa",
    "chuta": "chuta",
    "chute": "chute",
    "chuva": "chuva",
    "chaos": "ch\u00e3os",
    "ciano": "ciano",
    "ciclo": "ciclo",
    "cifra": "cifra",
    "cinco": "cinco",
    "cinta": "cinta",
    "cinto": "cinto",
    "cinza": "cinza",
    "cipos": "cip\u00f3s",
    "circo": "circo",
    "cisco": "cisco",
    "cisma": "cisma",
    "cisne": "cisne",
    "cisto": "cisto",
    "cisao": "cis\u00e3o",
    "citam": "citam",
    "citar": "citar",
    "citas": "citas",
    "citou": "citou",
    "civil": "civil",
    "civis": "civis",
    "ciume": "ci\u00fame",
    "clama": "clama",
    "clara": "clara",
    "claro": "claro",
    "clava": "clava",
    "clave": "clave",
    "clero": "clero",
    "clima": "clima",
    "clipe": "clipe",
    "clone": "clone",
    "cloro": "cloro",
    "clube": "clube",
    "cobra": "cobra",
    "cobre": "cobre",
    "cobri": "cobri",
    "cobro": "cobro",
    "cocho": "cocho",
    "cocos": "cocos",
    "coesa": "coesa",
    "coeso": "coeso",
    "cofre": "cofre",
    "coice": "coice",
    "coifa": "coifa",
    "coisa": "coisa",
    "coito": "coito",
    "colam": "colam",
    "colar": "colar",
    "colas": "colas",
    "colha": "colha",
    "colhe": "colhe",
    "colou": "colou",
    "comam": "comam",
    "comas": "comas",
    "comem": "comem",
    "comer": "comer",
    "comes": "comes",
    "comeu": "comeu",
    "comia": "comia",
    "comum": "comum",
    "conde": "conde",
    "cones": "cones",
    "conta": "conta",
    "conte": "conte",
    "conto": "conto",
    "copas": "copas",
    "copie": "copie",
    "copos": "copos",
    "coque": "coque",
    "coral": "coral",
    "corar": "corar",
    "corda": "corda",
    "cores": "cores",
    "corja": "corja",
    "corno": "corno",
    "coroa": "coroa",
    "coros": "coros",
    "corpo": "corpo",
    "corra": "corra",
    "corre": "corre",
    "corri": "corri",
    "corro": "corro",
    "corta": "corta",
    "corte": "corte",
    "corto": "corto",
    "corvo": "corvo",
    "corao": "cor\u00e3o",
    "corca": "cor\u00e7a",
    "coser": "coser",
    "cosmo": "cosmo",
    "cospe": "cospe",
    "costa": "costa",
    "cotas": "cotas",
    "cotia": "cotia",
    "coube": "coube",
    "couro": "couro",
    "cousa": "cousa",
    "couve": "couve",
    "covas": "covas",
    "covil": "covil",
    "coxas": "coxas",
    "cozer": "cozer",
    "cocam": "co\u00e7am",
    "cocar": "co\u00e7ar",
    "crase": "crase",
    "crava": "crava",
    "cravo": "cravo",
    "credo": "credo",
    "creem": "creem",
    "creia": "creia",
    "creio": "creio",
    "crema": "crema",
    "creme": "creme",
    "crepe": "crepe",
    "creta": "creta",
    "criam": "criam",
    "criar": "criar",
    "crias": "crias",
    "criei": "criei",
    "criem": "criem",
    "crime": "crime",
    "crina": "crina",
    "criou": "criou",
    "crise": "crise",
    "crivo": "crivo",
    "croma": "croma",
    "cromo": "cromo",
    "cruas": "cruas",
    "cruel": "cruel",
    "cruza": "cruza",
    "cubas": "cubas",
    "cubos": "cubos",
    "cubra": "cubra",
    "cueca": "cueca",
    "cuida": "cuida",
    "cuide": "cuide",
    "cuido": "cuido",
    "cujas": "cujas",
    "cujos": "cujos",
    "culpa": "culpa",
    "culta": "culta",
    "culto": "culto",
    "cumes": "cumes",
    "cunha": "cunha",
    "cunho": "cunho",
    "cupim": "cupim",
    "cupom": "cupom",
    "curam": "curam",
    "curar": "curar",
    "curou": "curou",
    "cursa": "cursa",
    "curso": "curso",
    "curta": "curta",
    "curte": "curte",
    "curti": "curti",
    "curto": "curto",
    "curva": "curva",
    "curvo": "curvo",
    "custa": "custa",
    "custe": "custe",
    "custo": "custo",
    "cuica": "cu\u00edca",
    "cesio": "c\u00e9sio",
    "cilio": "c\u00edlio",
    "cirio": "c\u00edrio",
    "civel": "c\u00edvel",
    "colon": "c\u00f3lon",
    "copia": "c\u00f3pia",
    "dados": "dados",
    "damas": "damas",
    "dando": "dando",
    "danos": "danos",
    "danca": "dan\u00e7a",
    "daqui": "daqui",
    "dardo": "dardo",
    "darei": "darei",
    "darem": "darem",
    "daria": "daria",
    "darao": "dar\u00e3o",
    "datam": "datam",
    "datar": "datar",
    "datas": "datas",
    "davam": "davam",
    "decai": "decai",
    "dedos": "dedos",
    "deduz": "deduz",
    "dedao": "ded\u00e3o",
    "deita": "deita",
    "deito": "deito",
    "deixa": "deixa",
    "deixe": "deixe",
    "deixo": "deixo",
    "delas": "delas",
    "deles": "deles",
    "demos": "demos",
    "demao": "dem\u00e3o",
    "dende": "dend\u00ea",
    "densa": "densa",
    "denso": "denso",
    "dente": "dente",
    "depor": "depor",
    "depos": "dep\u00f3s",
    "depoe": "dep\u00f5e",
    "deque": "deque",
    "deram": "deram",
    "derem": "derem",
    "derme": "derme",
    "desce": "desce",
    "desde": "desde",
    "despe": "despe",
    "dessa": "dessa",
    "desse": "desse",
    "desta": "desta",
    "deste": "deste",
    "desca": "des\u00e7a",
    "deter": "deter",
    "detem": "det\u00e9m",
    "deusa": "deusa",
    "devam": "devam",
    "devem": "devem",
    "dever": "dever",
    "deveu": "deveu",
    "devia": "devia",
    "diabo": "diabo",
    "dicas": "dicas",
    "dieta": "dieta",
    "digam": "digam",
    "digna": "digna",
    "digno": "digno",
    "dilui": "dilui",
    "dique": "dique",
    "direi": "direi",
    "diria": "diria",
    "dirao": "dir\u00e3o",
    "disco": "disco",
    "disse": "disse",
    "disso": "disso",
    "disto": "disto",
    "ditam": "ditam",
    "ditar": "ditar",
    "ditas": "ditas",
    "ditos": "ditos",
    "dizem": "dizem",
    "dizer": "dizer",
    "dizes": "dizes",
    "dizia": "dizia",
    "doada": "doada",
    "doado": "doado",
    "doara": "doara",
    "dobra": "dobra",
    "dobre": "dobre",
    "dobro": "dobro",
    "docas": "docas",
    "doces": "doces",
    "dogma": "dogma",
    "doida": "doida",
    "doido": "doido",
    "domar": "domar",
    "donas": "donas",
    "donos": "donos",
    "dores": "dores",
    "dorme": "dorme",
    "dormi": "dormi",
    "dorso": "dorso",
    "doses": "doses",
    "dotar": "dotar",
    "dotes": "dotes",
    "dotou": "dotou",
    "doura": "doura",
    "doiam": "do\u00edam",
    "draga": "draga",
    "drama": "drama",
    "drena": "drena",
    "dreno": "dreno",
    "droga": "droga",
    "dubla": "dubla",
    "duble": "dubl\u00ea",
    "ducha": "ducha",
    "duelo": "duelo",
    "dueto": "dueto",
    "dunas": "dunas",
    "dupla": "dupla",
    "duplo": "duplo",
    "duque": "duque",
    "duram": "duram",
    "durar": "durar",
    "duras": "duras",
    "durma": "durma",
    "duros": "duros",
    "durou": "durou",
    "durao": "dur\u00e3o",
    "dutos": "dutos",
    "debil": "d\u00e9bil",
    "docil": "d\u00f3cil",
    "dolar": "d\u00f3lar",
    "dubia": "d\u00fabia",
    "dubio": "d\u00fabio",
    "duzia": "d\u00fazia",
    "ebola": "ebola",
    "ecoam": "ecoam",
    "ecoar": "ecoar",
    "ecoou": "ecoou",
    "edema": "edema",
    "edita": "edita",
    "edite": "edite",
    "edito": "edito",
    "educa": "educa",
    "eixos": "eixos",
    "elege": "elege",
    "eleva": "eleva",
    "eleve": "eleve",
    "elite": "elite",
    "emana": "emana",
    "emite": "emite",
    "emula": "emula",
    "enche": "enche",
    "enfia": "enfia",
    "enfim": "enfim",
    "enjoa": "enjoa",
    "enjoo": "enjoo",
    "enoja": "enoja",
    "entes": "entes",
    "entoa": "entoa",
    "entra": "entra",
    "entre": "entre",
    "entro": "entro",
    "entao": "ent\u00e3o",
    "envia": "envia",
    "envie": "envie",
    "envio": "envio",
    "ereto": "ereto",
    "ergue": "ergue",
    "ermos": "ermos",
    "erram": "erram",
    "errar": "errar",
    "errei": "errei",
    "error": "error",
    "erros": "erros",
    "errou": "errou",
    "ervas": "ervas",
    "escoa": "escoa",
    "espia": "espia",
    "esqui": "esqui",
    "essas": "essas",
    "esses": "esses",
    "estar": "estar",
    "estas": "estas",
    "estes": "estes",
    "estou": "estou",
    "estao": "est\u00e3o",
    "esvai": "esvai",
    "etapa": "etapa",
    "etnia": "etnia",
    "euros": "euros",
    "evita": "evita",
    "evoca": "evoca",
    "exala": "exala",
    "exame": "exame",
    "exata": "exata",
    "exato": "exato",
    "exibe": "exibe",
    "exige": "exige",
    "exija": "exija",
    "expor": "expor",
    "expos": "exp\u00f4s",
    "expoe": "exp\u00f5e",
    "extra": "extra",
    "facas": "facas",
    "faces": "faces",
    "facho": "facho",
    "facao": "fac\u00e3o",
    "fadas": "fadas",
    "faixa": "faixa",
    "falam": "falam",
    "falar": "falar",
    "falas": "falas",
    "falei": "falei",
    "falem": "falem",
    "falha": "falha",
    "falhe": "falhe",
    "falho": "falho",
    "falir": "falir",
    "faliu": "faliu",
    "falou": "falou",
    "falsa": "falsa",
    "falso": "falso",
    "falta": "falta",
    "falte": "falte",
    "falto": "falto",
    "farda": "farda",
    "fardo": "fardo",
    "farei": "farei",
    "faria": "faria",
    "farol": "farol",
    "farpa": "farpa",
    "farra": "farra",
    "farsa": "farsa",
    "farta": "farta",
    "farto": "farto",
    "farao": "far\u00e3o",
    "fases": "fases",
    "fatal": "fatal",
    "fatia": "fatia",
    "fator": "fator",
    "fatos": "fatos",
    "fauna": "fauna",
    "favas": "favas",
    "favor": "favor",
    "favos": "favos",
    "fazem": "fazem",
    "fazer": "fazer",
    "fazes": "fazes",
    "fazia": "fazia",
    "facam": "fa\u00e7am",
    "febre": "febre",
    "fecal": "fecal",
    "fecha": "fecha",
    "feche": "feche",
    "fecho": "fecho",
    "feder": "feder",
    "fedor": "fedor",
    "feias": "feias",
    "feios": "feios",
    "feira": "feira",
    "feita": "feita",
    "feito": "feito",
    "feixe": "feixe",
    "feliz": "feliz",
    "fenda": "fenda",
    "feras": "feras",
    "ferem": "ferem",
    "feria": "feria",
    "ferir": "ferir",
    "feriu": "feriu",
    "feroz": "feroz",
    "ferra": "ferra",
    "ferre": "ferre",
    "ferro": "ferro",
    "ferve": "ferve",
    "festa": "festa",
    "fetal": "fetal",
    "fetos": "fetos",
    "feudo": "feudo",
    "fezes": "fezes",
    "fiada": "fiada",
    "fiado": "fiado",
    "fiapo": "fiapo",
    "fibra": "fibra",
    "ficam": "ficam",
    "ficar": "ficar",
    "ficha": "ficha",
    "ficou": "ficou",
    "figos": "figos",
    "filas": "filas",
    "filha": "filha",
    "filho": "filho",
    "filia": "filia",
    "filma": "filma",
    "filme": "filme",
    "filao": "fil\u00e3o",
    "final": "final",
    "finas": "finas",
    "finca": "finca",
    "finda": "finda",
    "findo": "findo",
    "finge": "finge",
    "finos": "finos",
    "finta": "finta",
    "fines": "fin\u00eas",
    "fique": "fique",
    "firma": "firma",
    "firme": "firme",
    "fisco": "fisco",
    "fisga": "fisga",
    "fitar": "fitar",
    "fitas": "fitas",
    "fixam": "fixam",
    "fixar": "fixar",
    "fixas": "fixas",
    "fixem": "fixem",
    "fixos": "fixos",
    "fixou": "fixou",
    "fizer": "fizer",
    "fieis": "fi\u00e9is",
    "flash": "flash",
    "floco": "floco",
    "flora": "flora",
    "fluem": "fluem",
    "fluir": "fluir",
    "fluxo": "fluxo",
    "fluor": "fl\u00faor",
    "fobia": "fobia",
    "focal": "focal",
    "focam": "focam",
    "focar": "focar",
    "focas": "focas",
    "focos": "focos",
    "focou": "focou",
    "fofas": "fofas",
    "fofos": "fofos",
    "fogem": "fogem",
    "fogos": "fogos",
    "fogao": "fog\u00e3o",
    "foice": "foice",
    "foles": "foles",
    "folga": "folga",
    "folha": "folha",
    "folia": "folia",
    "fomes": "fomes",
    "fomos": "fomos",
    "fones": "fones",
    "fonte": "fonte",
    "foram": "foram",
    "force": "force",
    "forem": "forem",
    "forja": "forja",
    "forma": "forma",
    "forme": "forme",
    "forno": "forno",
    "foros": "foros",
    "forra": "forra",
    "forro": "forr\u00f3",
    "forte": "forte",
    "forca": "for\u00e7a",
    "forco": "for\u00e7o",
    "fosca": "fosca",
    "fosco": "fosco",
    "fossa": "fossa",
    "fosse": "fosse",
    "fosso": "fosso",
    "fotos": "fotos",
    "fraca": "fraca",
    "fraco": "fraco",
    "frade": "frade",
    "fraga": "fraga",
    "frase": "frase",
    "frear": "frear",
    "freio": "freio",
    "fresa": "fresa",
    "frete": "frete",
    "frias": "frias",
    "frios": "frios",
    "frisa": "frisa",
    "friso": "friso",
    "frita": "frita",
    "frito": "frito",
    "frota": "frota",
    "fruta": "fruta",
    "fruto": "fruto",
    "fugas": "fugas",
    "fugaz": "fugaz",
    "fugia": "fugia",
    "fugir": "fugir",
    "fugiu": "fugiu",
    "fujam": "fujam",
    "fumar": "fumar",
    "fumos": "fumos",
    "fumou": "fumou",
    "funda": "funda",
    "funde": "funde",
    "fundo": "fundo",
    "fungo": "fungo",
    "funil": "funil",
    "furar": "furar",
    "furor": "furor",
    "furos": "furos",
    "furou": "furou",
    "furta": "furta",
    "furto": "furto",
    "furao": "fur\u00e3o",
    "fusca": "fusca",
    "fusco": "fusco",
    "fusos": "fusos",
    "fusao": "fus\u00e3o",
    "fuzil": "fuzil",
    "fuzis": "fuzis",
    "fucas": "fu\u00e7as",
    "facil": "f\u00e1cil",
    "femea": "f\u00eamea",
    "femur": "f\u00eamur",
    "fenix": "f\u00eanix",
    "folio": "f\u00f3lio",
    "forum": "f\u00f3rum",
    "foton": "f\u00f3ton",
    "furia": "f\u00faria",
    "futil": "f\u00fatil",
    "gabar": "gabar",
    "gados": "gados",
    "gaita": "gaita",
    "galas": "galas",
    "galho": "galho",
    "galos": "galos",
    "galao": "gal\u00e3o",
    "gamba": "gamba",
    "ganha": "ganha",
    "ganhe": "ganhe",
    "ganho": "ganho",
    "ganso": "ganso",
    "garfo": "garfo",
    "garoa": "garoa",
    "garra": "garra",
    "garca": "gar\u00e7a",
    "gases": "gases",
    "gasta": "gasta",
    "gaste": "gaste",
    "gasto": "gasto",
    "gatas": "gatas",
    "gatos": "gatos",
    "geada": "geada",
    "gelos": "gelos",
    "gemas": "gemas",
    "gemia": "gemia",
    "genes": "genes",
    "genro": "genro",
    "gente": "gente",
    "geral": "geral",
    "geram": "geram",
    "gerar": "gerar",
    "gerir": "gerir",
    "germe": "germe",
    "gerou": "gerou",
    "gesso": "gesso",
    "gibis": "gibis",
    "ginga": "ginga",
    "giram": "giram",
    "girar": "girar",
    "giros": "giros",
    "girou": "girou",
    "glace": "glac\u00ea",
    "globo": "globo",
    "goela": "goela",
    "golfe": "golfe",
    "golfo": "golfo",
    "golpe": "golpe",
    "gomas": "gomas",
    "gomos": "gomos",
    "gongo": "gongo",
    "gorda": "gorda",
    "gordo": "gordo",
    "gorro": "gorro",
    "gosma": "gosma",
    "gosta": "gosta",
    "goste": "goste",
    "gosto": "gosto",
    "gotas": "gotas",
    "gozam": "gozam",
    "gozar": "gozar",
    "gozou": "gozou",
    "grade": "grade",
    "grado": "grado",
    "grama": "grama",
    "grana": "grana",
    "grata": "grata",
    "grato": "grato",
    "graus": "graus",
    "grava": "grava",
    "grave": "grave",
    "gravo": "gravo",
    "graxa": "graxa",
    "graca": "gra\u00e7a",
    "grega": "grega",
    "grego": "grego",
    "grena": "gren\u00e1",
    "greve": "greve",
    "grife": "grife",
    "grifo": "grifo",
    "grilo": "grilo",
    "gripe": "gripe",
    "grita": "grita",
    "grito": "grito",
    "grosa": "grosa",
    "gruda": "gruda",
    "grupo": "grupo",
    "gruta": "gruta",
    "graos": "gr\u00e3os",
    "gueto": "gueto",
    "guiam": "guiam",
    "guiar": "guiar",
    "guias": "guias",
    "guida": "guida",
    "guina": "guina",
    "guiou": "guiou",
    "gumes": "gumes",
    "gavea": "g\u00e1vea",
    "gemea": "g\u00eamea",
    "gemeo": "g\u00eameo",
    "genio": "g\u00eanio",
    "giria": "g\u00edria",
    "harpa": "harpa",
    "harem": "har\u00e9m",
    "haste": "haste",
    "haver": "haver",
    "havia": "havia",
    "herda": "herda",
    "heroi": "her\u00f3i",
    "hiato": "hiato",
    "hidra": "hidra",
    "hidro": "hidro",
    "hiena": "hiena",
    "hindu": "hindu",
    "hinos": "hinos",
    "hiper": "hiper",
    "hobby": "hobby",
    "homem": "homem",
    "honra": "honra",
    "horas": "horas",
    "horda": "horda",
    "horta": "horta",
    "horto": "horto",
    "hotel": "hotel",
    "houve": "houve",
    "humor": "humor",
    "habil": "h\u00e1bil",
    "hifen": "h\u00edfen",
    "himen": "h\u00edmen",
    "hindi": "h\u00edndi",
    "humus": "h\u00famus",
    "idade": "idade",
    "ideal": "ideal",
    "idosa": "idosa",
    "idoso": "idoso",
    "ideia": "id\u00e9ia",
    "igual": "igual",
    "ileso": "ileso",
    "ilhas": "ilhas",
    "ilheu": "ilh\u00e9u",
    "imita": "imita",
    "impor": "impor",
    "impos": "imp\u00f4s",
    "impoe": "imp\u00f5e",
    "imune": "imune",
    "inata": "inata",
    "inato": "inato",
    "incha": "incha",
    "induz": "induz",
    "infla": "infla",
    "inibe": "inibe",
    "inova": "inova",
    "intra": "intra",
    "intui": "intui",
    "inves": "inv\u00e9s",
    "irada": "irada",
    "irado": "irado",
    "iriam": "iriam",
    "irmos": "irmos",
    "irmao": "irm\u00e3o",
    "irmas": "irm\u00e3s",
    "iscas": "iscas",
    "isola": "isola",
    "istmo": "istmo",
    "itens": "itens",
    "icara": "i\u00e7ara",
    "janta": "janta",
    "jarda": "jarda",
    "jarra": "jarra",
    "jarro": "jarro",
    "jatos": "jatos",
    "jaula": "jaula",
    "jazem": "jazem",
    "jeans": "jeans",
    "jegue": "jegue",
    "jeito": "jeito",
    "jejum": "jejum",
    "jogam": "jogam",
    "jogar": "jogar",
    "jogos": "jogos",
    "jogou": "jogou",
    "jogue": "jogue",
    "jorra": "jorra",
    "jorro": "jorro",
    "jovem": "jovem",
    "judeu": "judeu",
    "judia": "judia",
    "julga": "julga",
    "julgo": "julgo",
    "julho": "julho",
    "junco": "junco",
    "junho": "junho",
    "junta": "junta",
    "junte": "junte",
    "junto": "junto",
    "jurar": "jurar",
    "juris": "juris",
    "juros": "juros",
    "jurou": "jurou",
    "justa": "justa",
    "justo": "justo",
    "juiza": "ju\u00edza",
    "juizo": "ju\u00edzo",
    "joias": "j\u00f3ias",
    "karma": "karma",
    "lacre": "lacre",
    "lacta": "lacta",
    "lados": "lados",
    "ladra": "ladra",
    "lages": "lages",
    "lagoa": "lagoa",
    "lagos": "lagos",
    "laico": "laico",
    "lajes": "lajes",
    "lamas": "lamas",
    "lamba": "lamba",
    "lambe": "lambe",
    "lance": "lance",
    "lanca": "lan\u00e7a",
    "lanco": "lan\u00e7o",
    "lapas": "lapas",
    "lapso": "lapso",
    "laque": "laqu\u00ea",
    "lares": "lares",
    "larga": "larga",
    "largo": "largo",
    "larva": "larva",
    "lasca": "lasca",
    "laser": "laser",
    "latas": "latas",
    "latim": "latim",
    "latir": "latir",
    "latao": "lat\u00e3o",
    "laudo": "laudo",
    "lavam": "lavam",
    "lavar": "lavar",
    "lavas": "lavas",
    "lavou": "lavou",
    "lavra": "lavra",
    "lazer": "lazer",
    "lacar": "la\u00e7ar",
    "lacos": "la\u00e7os",
    "lacao": "la\u00e7\u00e3o",
    "leais": "leais",
    "lebre": "lebre",
    "legal": "legal",
    "legar": "legar",
    "legou": "legou",
    "leiam": "leiam",
    "leiga": "leiga",
    "leigo": "leigo",
    "leira": "leira",
    "leite": "leite",
    "leito": "leito",
    "lemas": "lemas",
    "lemes": "lemes",
    "lemos": "lemos",
    "lenda": "lenda",
    "lenha": "lenha",
    "lenta": "lenta",
    "lente": "lente",
    "lento": "lento",
    "lenco": "len\u00e7o",
    "lepra": "lepra",
    "leque": "leque",
    "leram": "leram",
    "lerem": "lerem",
    "leria": "leria",
    "lesar": "lesar",
    "lesma": "lesma",
    "leste": "leste",
    "lesao": "les\u00e3o",
    "letal": "letal",
    "letra": "letra",
    "levam": "levam",
    "levar": "levar",
    "levas": "levas",
    "levei": "levei",
    "levem": "levem",
    "leves": "leves",
    "levou": "levou",
    "leoes": "le\u00f5es",
    "libra": "libra",
    "licor": "licor",
    "lidam": "lidam",
    "lidar": "lidar",
    "lidas": "lidas",
    "lidos": "lidos",
    "ligam": "ligam",
    "ligar": "ligar",
    "ligou": "ligou",
    "lilas": "lil\u00e1s",
    "limar": "limar",
    "limbo": "limbo",
    "limpa": "limpa",
    "limpo": "limpo",
    "limao": "lim\u00e3o",
    "lince": "lince",
    "linda": "linda",
    "lindo": "lindo",
    "linfa": "linfa",
    "linha": "linha",
    "linho": "linho",
    "lisas": "lisas",
    "lisos": "lisos",
    "lista": "lista",
    "litro": "litro",
    "lives": "lives",
    "livra": "livra",
    "livre": "livre",
    "livro": "livro",
    "lixos": "lixos",
    "lixao": "lix\u00e3o",
    "licao": "li\u00e7\u00e3o",
    "lobos": "lobos",
    "local": "local",
    "locar": "locar",
    "logra": "logra",
    "logro": "logro",
    "loira": "loira",
    "loiro": "loiro",
    "lojas": "lojas",
    "lomba": "lomba",
    "lombo": "lombo",
    "lonas": "lonas",
    "longa": "longa",
    "longe": "longe",
    "longo": "longo",
    "lorde": "lorde",
    "lotar": "lotar",
    "lotes": "lotes",
    "lotou": "lotou",
    "louca": "louca",
    "louco": "louco",
    "loura": "loura",
    "louro": "louro",
    "lousa": "lousa",
    "louva": "louva",
    "locao": "lo\u00e7\u00e3o",
    "lucra": "lucra",
    "lucro": "lucro",
    "lugar": "lugar",
    "lulas": "lulas",
    "lumes": "lumes",
    "lunar": "lunar",
    "lutam": "lutam",
    "lutar": "lutar",
    "lutas": "lutas",
    "lutou": "lutou",
    "luvas": "luvas",
    "luxos": "luxos",
    "luzes": "luzes",
    "luzia": "luzia",
    "labia": "l\u00e1bia",
    "labio": "l\u00e1bio",
    "lapis": "l\u00e1pis",
    "latex": "l\u00e1tex",
    "legua": "l\u00e9gua",
    "lider": "l\u00edder",
    "lirio": "l\u00edrio",
    "litio": "l\u00edtio",
    "lupus": "l\u00fapus",
    "macho": "macho",
    "mache": "mach\u00ea",
    "macia": "macia",
    "macio": "macio",
    "macro": "macro",
    "madre": "madre",
    "magia": "magia",
    "magma": "magma",
    "magna": "magna",
    "magno": "magno",
    "magos": "magos",
    "magra": "magra",
    "magro": "magro",
    "maior": "maior",
    "major": "major",
    "malas": "malas",
    "males": "males",
    "malha": "malha",
    "malho": "malho",
    "malte": "malte",
    "mamam": "mamam",
    "mamar": "mamar",
    "mamas": "mamas",
    "mamae": "mam\u00e3e",
    "mamao": "mam\u00e3o",
    "manas": "manas",
    "manca": "manca",
    "manco": "manco",
    "manda": "manda",
    "mande": "mande",
    "mando": "mando",
    "manes": "manes",
    "manga": "manga",
    "manha": "manh\u00e3",
    "mania": "mania",
    "manja": "manja",
    "manos": "manos",
    "mansa": "mansa",
    "manso": "manso",
    "manta": "manta",
    "manto": "manto",
    "mapas": "mapas",
    "marca": "marca",
    "marco": "marco",
    "mares": "mares",
    "marra": "marra",
    "marte": "marte",
    "massa": "massa",
    "matam": "matam",
    "matar": "matar",
    "matas": "matas",
    "matem": "matem",
    "matiz": "matiz",
    "matos": "matos",
    "matou": "matou",
    "macas": "ma\u00e7\u00e3s",
    "meada": "meada",
    "mecha": "mecha",
    "medem": "medem",
    "medir": "medir",
    "mediu": "mediu",
    "medos": "medos",
    "meias": "meias",
    "meiga": "meiga",
    "meigo": "meigo",
    "meios": "meios",
    "melao": "mel\u00e3o",
    "menor": "menor",
    "menos": "menos",
    "menta": "menta",
    "mente": "mente",
    "mento": "mento",
    "meras": "meras",
    "merce": "merc\u00ea",
    "merda": "merda",
    "meros": "meros",
    "mesas": "mesas",
    "meses": "meses",
    "mesma": "mesma",
    "mesmo": "mesmo",
    "messa": "messa",
    "messe": "messe",
    "metal": "metal",
    "metas": "metas",
    "meter": "meter",
    "meteu": "meteu",
    "metro": "metro",
    "mexem": "mexem",
    "mexer": "mexer",
    "mexeu": "mexeu",
    "mexia": "mexia",
    "micha": "micha",
    "micos": "micos",
    "micro": "micro",
    "midas": "midas",
    "migra": "migra",
    "milha": "milha",
    "milho": "milho",
    "mimos": "mimos",
    "minam": "minam",
    "minar": "minar",
    "minas": "minas",
    "minha": "minha",
    "miolo": "miolo",
    "miram": "miram",
    "mirar": "mirar",
    "miras": "miras",
    "mirim": "mirim",
    "mirra": "mirra",
    "missa": "missa",
    "mista": "mista",
    "misto": "misto",
    "mitos": "mitos",
    "miuda": "mi\u00fada",
    "miudo": "mi\u00fado",
    "modas": "modas",
    "modem": "modem",
    "modos": "modos",
    "moeda": "moeda",
    "moela": "moela",
    "mogno": "mogno",
    "moita": "moita",
    "molar": "molar",
    "molas": "molas",
    "molda": "molda",
    "molde": "molde",
    "moles": "moles",
    "molha": "molha",
    "molhe": "molhe",
    "molho": "molho",
    "monge": "monge",
    "monja": "monja",
    "monta": "monta",
    "monte": "monte",
    "monto": "monto",
    "moral": "moral",
    "moram": "moram",
    "morar": "morar",
    "morde": "morde",
    "morna": "morna",
    "morno": "morno",
    "morou": "morou",
    "morra": "morra",
    "morre": "morre",
    "morri": "morri",
    "morro": "morro",
    "morta": "morta",
    "morte": "morte",
    "morto": "morto",
    "mosca": "mosca",
    "mossa": "mossa",
    "motel": "motel",
    "motim": "motim",
    "motor": "motor",
    "motos": "motos",
    "moura": "moura",
    "mouro": "mouro",
    "movem": "movem",
    "mover": "mover",
    "moveu": "moveu",
    "movia": "movia",
    "mocas": "mo\u00e7as",
    "mocos": "mo\u00e7os",
    "moida": "mo\u00edda",
    "moido": "mo\u00eddo",
    "mudam": "mudam",
    "mudar": "mudar",
    "mudas": "mudas",
    "mudei": "mudei",
    "mudem": "mudem",
    "mudez": "mudez",
    "mudos": "mudos",
    "mudou": "mudou",
    "muita": "muita",
    "muito": "muito",
    "mulas": "mulas",
    "multa": "multa",
    "multi": "multi",
    "mundo": "mundo",
    "mural": "mural",
    "muros": "muros",
    "murro": "murro",
    "murta": "murta",
    "musas": "musas",
    "museu": "museu",
    "musgo": "musgo",
    "mafia": "m\u00e1fia",
    "magoa": "m\u00e1goa",
    "media": "m\u00e9dia",
    "medio": "m\u00e9dio",
    "midia": "m\u00eddia",
    "miope": "m\u00edope",
    "movel": "m\u00f3vel",
    "mumia": "m\u00famia",
    "mutua": "m\u00fatua",
    "mutuo": "m\u00fatuo",
    "nadam": "nadam",
    "nadar": "nadar",
    "naipe": "naipe",
    "nariz": "nariz",
    "narra": "narra",
    "nasal": "nasal",
    "nasce": "nasce",
    "nasci": "nasci",
    "nasca": "nas\u00e7a",
    "natal": "natal",
    "natos": "natos",
    "naval": "naval",
    "naves": "naves",
    "navio": "navio",
    "nacao": "na\u00e7\u00e3o",
    "negam": "negam",
    "negar": "negar",
    "negou": "negou",
    "negra": "negra",
    "negro": "negro",
    "negue": "negue",
    "nelas": "nelas",
    "neles": "neles",
    "nenem": "nen\u00e9m",
    "nervo": "nervo",
    "nessa": "nessa",
    "nesse": "nesse",
    "nesta": "nesta",
    "neste": "neste",
    "netas": "netas",
    "netos": "netos",
    "neura": "neura",
    "neuro": "neuro",
    "nevar": "nevar",
    "nicho": "nicho",
    "ninar": "ninar",
    "ninfa": "ninfa",
    "ninha": "ninha",
    "ninho": "ninho",
    "ninja": "ninja",
    "nisso": "nisso",
    "nisto": "nisto",
    "nitro": "nitro",
    "nobel": "nobel",
    "nobre": "nobre",
    "noite": "noite",
    "noiva": "noiva",
    "noivo": "noivo",
    "nomes": "nomes",
    "noras": "noras",
    "norma": "norma",
    "norte": "norte",
    "nossa": "nossa",
    "nosso": "nosso",
    "notam": "notam",
    "notar": "notar",
    "notas": "notas",
    "notei": "notei",
    "notou": "notou",
    "novas": "novas",
    "noves": "noves",
    "novos": "novos",
    "nozes": "nozes",
    "nocao": "no\u00e7\u00e3o",
    "nudez": "nudez",
    "nulas": "nulas",
    "nulos": "nulos",
    "numas": "numas",
    "nunca": "nunca",
    "nutre": "nutre",
    "nutri": "nutri",
    "nuvem": "nuvem",
    "nevoa": "n\u00e9voa",
    "nivel": "n\u00edvel",
    "obesa": "obesa",
    "obeso": "obeso",
    "obras": "obras",
    "obter": "obter",
    "obtem": "obt\u00e9m",
    "ocupa": "ocupa",
    "ocupe": "ocupe",
    "odeia": "odeia",
    "odeio": "odeio",
    "odiar": "odiar",
    "oeste": "oeste",
    "ogiva": "ogiva",
    "olham": "olham",
    "olhar": "olhar",
    "olhei": "olhei",
    "olhem": "olhem",
    "olhos": "olhos",
    "olhou": "olhou",
    "oliva": "oliva",
    "ombro": "ombro",
    "omite": "omite",
    "ondas": "ondas",
    "onera": "onera",
    "ontem": "ontem",
    "oncas": "on\u00e7as",
    "opaca": "opaca",
    "opaco": "opaco",
    "opera": "opera",
    "opere": "opere",
    "opina": "opina",
    "optam": "optam",
    "optar": "optar",
    "optei": "optei",
    "optou": "optou",
    "opcao": "op\u00e7\u00e3o",
    "opoem": "op\u00f5em",
    "orais": "orais",
    "orcas": "orcas",
    "ordem": "ordem",
    "orgia": "orgia",
    "oscar": "oscar",
    "ossos": "ossos",
    "ostra": "ostra",
    "ouros": "ouros",
    "ousam": "ousam",
    "ousar": "ousar",
    "ousou": "ousou",
    "outra": "outra",
    "outro": "outro",
    "ouvem": "ouvem",
    "ouvia": "ouvia",
    "ouvir": "ouvir",
    "ouviu": "ouviu",
    "oucam": "ou\u00e7am",
    "ovais": "ovais",
    "oxida": "oxida",
    "oasis": "o\u00e1sis",
    "padre": "padre",
    "pagam": "pagam",
    "pagar": "pagar",
    "pagas": "pagas",
    "pagos": "pagos",
    "pagou": "pagou",
    "pague": "pague",
    "pagao": "pag\u00e3o",
    "paiol": "paiol",
    "paira": "paira",
    "palco": "palco",
    "palha": "palha",
    "palma": "palma",
    "palmo": "palmo",
    "panca": "panca",
    "panda": "panda",
    "panos": "panos",
    "papai": "papai",
    "papal": "papal",
    "papas": "papas",
    "papel": "papel",
    "papos": "papos",
    "param": "param",
    "parar": "parar",
    "parda": "parda",
    "pardo": "pardo",
    "parei": "parei",
    "parem": "parem",
    "paria": "paria",
    "parir": "parir",
    "pariu": "pariu",
    "parou": "parou",
    "parta": "parta",
    "parte": "parte",
    "parti": "parti",
    "parto": "parto",
    "pasma": "pasma",
    "pasmo": "pasmo",
    "passa": "passa",
    "passe": "passe",
    "passo": "passo",
    "pasta": "pasta",
    "pasto": "pasto",
    "patas": "patas",
    "patos": "patos",
    "pausa": "pausa",
    "pauta": "pauta",
    "pavio": "pavio",
    "pavor": "pavor",
    "pavao": "pav\u00e3o",
    "pazes": "pazes",
    "pacos": "pa\u00e7os",
    "pecar": "pecar",
    "pecou": "pecou",
    "pedal": "pedal",
    "pedem": "pedem",
    "pedia": "pedia",
    "pedir": "pedir",
    "pediu": "pediu",
    "pedra": "pedra",
    "pegam": "pegam",
    "pegar": "pegar",
    "pegou": "pegou",
    "pegue": "pegue",
    "peida": "peida",
    "peito": "peito",
    "peixe": "peixe",
    "pelas": "pelas",
    "peles": "peles",
    "pelos": "pelos",
    "pelve": "pelve",
    "penal": "penal",
    "penar": "penar",
    "penas": "penas",
    "penca": "penca",
    "pende": "pende",
    "pensa": "pensa",
    "pense": "pense",
    "penso": "penso",
    "penta": "penta",
    "pente": "pente",
    "peras": "peras",
    "perca": "perca",
    "perco": "perco",
    "perda": "perda",
    "perde": "perde",
    "perdi": "perdi",
    "peres": "peres",
    "perna": "perna",
    "persa": "persa",
    "perto": "perto",
    "perua": "perua",
    "perus": "perus",
    "pesam": "pesam",
    "pesar": "pesar",
    "pesca": "pesca",
    "pesos": "pesos",
    "pesou": "pesou",
    "peste": "peste",
    "pecam": "pe\u00e7am",
    "pecas": "pe\u00e7as",
    "peoes": "pe\u00f5es",
    "piada": "piada",
    "piano": "piano",
    "picar": "picar",
    "picas": "picas",
    "piche": "piche",
    "picos": "picos",
    "picao": "pic\u00e3o",
    "pilha": "pilha",
    "pilao": "pil\u00e3o",
    "pinga": "pinga",
    "pingo": "pingo",
    "pinha": "pinha",
    "pinho": "pinho",
    "pinos": "pinos",
    "pinta": "pinta",
    "pinto": "pinto",
    "pinca": "pin\u00e7a",
    "piora": "piora",
    "pipas": "pipas",
    "pique": "pique",
    "pirar": "pirar",
    "pires": "pires",
    "pisar": "pisar",
    "pisca": "pisca",
    "pisos": "pisos",
    "pisou": "pisou",
    "pista": "pista",
    "pizza": "pizza",
    "placa": "placa",
    "plana": "plana",
    "plano": "plano",
    "plato": "plat\u00f4",
    "plebe": "plebe",
    "plena": "plena",
    "pleno": "pleno",
    "plexo": "plexo",
    "pluma": "pluma",
    "pneus": "pneus",
    "pobre": "pobre",
    "podar": "podar",
    "podas": "podas",
    "podem": "podem",
    "poder": "poder",
    "podes": "podes",
    "podia": "podia",
    "podre": "podre",
    "poema": "poema",
    "poeta": "poeta",
    "polar": "polar",
    "polia": "polia",
    "polir": "polir",
    "polos": "polos",
    "polpa": "polpa",
    "polui": "polui",
    "polvo": "polvo",
    "pomar": "pomar",
    "pomba": "pomba",
    "pombo": "pombo",
    "pomos": "pomos",
    "pompa": "pompa",
    "ponde": "ponde",
    "pondo": "pondo",
    "ponha": "ponha",
    "ponho": "ponho",
    "ponta": "ponta",
    "ponte": "ponte",
    "ponto": "ponto",
    "porca": "porca",
    "porco": "porco",
    "poria": "poria",
    "poros": "poros",
    "porra": "porra",
    "porre": "porre",
    "porro": "porro",
    "porta": "porta",
    "porte": "porte",
    "porto": "porto",
    "porao": "por\u00e3o",
    "porem": "por\u00e9m",
    "poses": "poses",
    "possa": "possa",
    "posse": "posse",
    "posso": "posso",
    "posta": "posta",
    "poste": "poste",
    "posto": "posto",
    "potes": "potes",
    "pouca": "pouca",
    "pouco": "pouco",
    "poupa": "poupa",
    "pousa": "pousa",
    "pouso": "pouso",
    "povos": "povos",
    "pocas": "po\u00e7as",
    "pocos": "po\u00e7os",
    "pocao": "po\u00e7\u00e3o",
    "prado": "prado",
    "praga": "praga",
    "praia": "praia",
    "prata": "prata",
    "prato": "prato",
    "praxe": "praxe",
    "prazo": "prazo",
    "praca": "pra\u00e7a",
    "prece": "prece",
    "prega": "prega",
    "prego": "prego",
    "presa": "presa",
    "preso": "preso",
    "preta": "preta",
    "preto": "preto",
    "previ": "previ",
    "preve": "prev\u00ea",
    "preza": "preza",
    "preze": "preze",
    "prezo": "prezo",
    "preco": "pre\u00e7o",
    "prima": "prima",
    "primo": "primo",
    "priva": "priva",
    "prive": "prive",
    "prole": "prole",
    "prosa": "prosa",
    "prova": "prova",
    "prove": "prove",
    "prumo": "prumo",
    "psico": "psico",
    "puder": "puder",
    "pudim": "pudim",
    "pudor": "pudor",
    "pugna": "pugna",
    "pulam": "pulam",
    "pular": "pular",
    "pulga": "pulga",
    "pulos": "pulos",
    "pulou": "pulou",
    "pulsa": "pulsa",
    "pulso": "pulso",
    "punha": "punha",
    "punho": "punho",
    "punir": "punir",
    "puniu": "puniu",
    "puras": "puras",
    "purga": "purga",
    "puros": "puros",
    "putas": "putas",
    "puxam": "puxam",
    "puxar": "puxar",
    "puxou": "puxou",
    "puxao": "pux\u00e3o",
    "pareo": "p\u00e1reo",
    "patio": "p\u00e1tio",
    "penis": "p\u00eanis",
    "pifio": "p\u00edfio",
    "piton": "p\u00edton",
    "podio": "p\u00f3dio",
    "polen": "p\u00f3len",
    "polio": "p\u00f3lio",
    "povoa": "p\u00f3voa",
    "ponei": "p\u00f4nei",
    "pubis": "p\u00fabis",
    "quais": "quais",
    "quase": "quase",
    "queda": "queda",
    "quero": "quero",
    "quilo": "quilo",
    "quina": "quina",
    "quite": "quite",
    "quica": "qui\u00e7\u00e1",
    "quota": "quota",
    "rabos": "rabos",
    "rabao": "rab\u00e3o",
    "racha": "racha",
    "radar": "radar",
    "raiar": "raiar",
    "raias": "raias",
    "raios": "raios",
    "raiva": "raiva",
    "ralar": "ralar",
    "ralha": "ralha",
    "ramal": "ramal",
    "ramas": "ramas",
    "ramos": "ramos",
    "rampa": "rampa",
    "ranco": "ran\u00e7o",
    "rapaz": "rapaz",
    "rapta": "rapta",
    "rapto": "rapto",
    "raras": "raras",
    "raros": "raros",
    "rasas": "rasas",
    "rasga": "rasga",
    "rasgo": "rasgo",
    "rasos": "rasos",
    "raspa": "raspa",
    "rasto": "rasto",
    "ratos": "ratos",
    "razao": "raz\u00e3o",
    "racas": "ra\u00e7as",
    "racao": "ra\u00e7\u00e3o",
    "reage": "reage",
    "reais": "reais",
    "recai": "recai",
    "recua": "recua",
    "recuo": "recuo",
    "recem": "rec\u00e9m",
    "redes": "redes",
    "redor": "redor",
    "reduz": "reduz",
    "refaz": "refaz",
    "refez": "refez",
    "refem": "ref\u00e9m",
    "regar": "regar",
    "regem": "regem",
    "reger": "reger",
    "regra": "regra",
    "reina": "reina",
    "reino": "reino",
    "reles": "reles",
    "reluz": "reluz",
    "relva": "relva",
    "remar": "remar",
    "remos": "remos",
    "renal": "renal",
    "renda": "renda",
    "rende": "rende",
    "rente": "rente",
    "repor": "repor",
    "repoe": "rep\u00f5e",
    "resta": "resta",
    "resto": "resto",
    "retal": "retal",
    "retas": "retas",
    "reter": "reter",
    "retos": "retos",
    "retro": "retr\u00f4",
    "retem": "ret\u00e9m",
    "rever": "rever",
    "reviu": "reviu",
    "reves": "rev\u00e9s",
    "rezam": "rezam",
    "rezar": "rezar",
    "rezas": "rezas",
    "reuna": "re\u00fana",
    "reune": "re\u00fane",
    "reuso": "re\u00faso",
    "ricas": "ricas",
    "ricos": "ricos",
    "rifle": "rifle",
    "rigor": "rigor",
    "rimar": "rimar",
    "rimas": "rimas",
    "rindo": "rindo",
    "rinha": "rinha",
    "ripas": "ripas",
    "risca": "risca",
    "risco": "risco",
    "risos": "risos",
    "ritmo": "ritmo",
    "ritos": "ritos",
    "rival": "rival",
    "rixas": "rixas",
    "robos": "rob\u00f4s",
    "rocha": "rocha",
    "rodam": "rodam",
    "rodar": "rodar",
    "rodas": "rodas",
    "rodou": "rodou",
    "rogar": "rogar",
    "rojao": "roj\u00e3o",
    "rolam": "rolam",
    "rolar": "rolar",
    "rolha": "rolha",
    "rolos": "rolos",
    "rolou": "rolou",
    "rombo": "rombo",
    "rompe": "rompe",
    "ronca": "ronca",
    "ronco": "ronco",
    "ronda": "ronda",
    "rosas": "rosas",
    "rosca": "rosca",
    "rosna": "rosna",
    "rosto": "rosto",
    "rotas": "rotas",
    "rotor": "rotor",
    "rouba": "rouba",
    "roubo": "roubo",
    "rouca": "rouca",
    "rouco": "rouco",
    "roupa": "roupa",
    "roxas": "roxas",
    "roxos": "roxos",
    "rocam": "ro\u00e7am",
    "rocar": "ro\u00e7ar",
    "rocas": "ro\u00e7as",
    "rubis": "rubis",
    "rubro": "rubro",
    "rudes": "rudes",
    "ruela": "ruela",
    "rugas": "rugas",
    "ruins": "ruins",
    "ruiva": "ruiva",
    "ruivo": "ruivo",
    "rumar": "rumar",
    "rumor": "rumor",
    "rumos": "rumos",
    "rural": "rural",
    "russa": "russa",
    "russo": "russo",
    "ruido": "ru\u00eddo",
    "ruina": "ru\u00edna",
    "radio": "r\u00e1dio",
    "redea": "r\u00e9dea",
    "regia": "r\u00e9gia",
    "regio": "r\u00e9gio",
    "regua": "r\u00e9gua",
    "rimel": "r\u00edmel",
    "rosea": "r\u00f3sea",
    "roseo": "r\u00f3seo",
    "sabem": "sabem",
    "saber": "saber",
    "sabia": "sabia",
    "sabor": "sabor",
    "sabre": "sabre",
    "sabao": "sab\u00e3o",
    "sacar": "sacar",
    "sacas": "sacas",
    "sache": "sach\u00ea",
    "sacia": "sacia",
    "sacos": "sacos",
    "sacra": "sacra",
    "sacro": "sacro",
    "sadia": "sadia",
    "sadio": "sadio",
    "safar": "safar",
    "safra": "safra",
    "sagaz": "sagaz",
    "saiam": "saiam",
    "saias": "saias",
    "saiba": "saiba",
    "saira": "sair\u00e1",
    "salas": "salas",
    "saldo": "saldo",
    "salga": "salga",
    "salmo": "salmo",
    "salsa": "salsa",
    "salta": "salta",
    "salto": "salto",
    "salva": "salva",
    "salve": "salve",
    "salvo": "salvo",
    "salao": "sal\u00e3o",
    "samba": "samba",
    "sanar": "sanar",
    "santa": "santa",
    "santo": "santo",
    "sapos": "sapos",
    "saque": "saque",
    "sarau": "sarau",
    "sarja": "sarja",
    "sarna": "sarna",
    "sarro": "sarro",
    "sarca": "sar\u00e7a",
    "sauna": "sauna",
    "saxao": "sax\u00e3o",
    "saida": "sa\u00edda",
    "saido": "sa\u00eddo",
    "sauda": "sa\u00fada",
    "saude": "sa\u00fade",
    "saudo": "sa\u00fado",
    "secam": "secam",
    "secar": "secar",
    "secas": "secas",
    "secos": "secos",
    "secou": "secou",
    "sedes": "sedes",
    "sedia": "sedia",
    "seduz": "seduz",
    "segue": "segue",
    "segui": "segui",
    "seios": "seios",
    "seita": "seita",
    "seiva": "seiva",
    "seixo": "seixo",
    "sejam": "sejam",
    "selar": "selar",
    "selim": "selim",
    "selos": "selos",
    "selou": "selou",
    "selva": "selva",
    "sendo": "sendo",
    "senha": "senha",
    "senil": "senil",
    "senso": "senso",
    "senta": "senta",
    "sente": "sente",
    "senti": "senti",
    "sento": "sento",
    "senao": "sen\u00e3o",
    "sepse": "sepse",
    "septo": "septo",
    "seque": "seque",
    "serei": "serei",
    "serem": "serem",
    "seres": "seres",
    "seria": "seria",
    "serra": "serra",
    "serva": "serva",
    "serve": "serve",
    "servi": "servi",
    "servo": "servo",
    "seras": "ser\u00e1s",
    "serao": "ser\u00e3o",
    "sesta": "sesta",
    "setas": "setas",
    "setor": "setor",
    "sexos": "sexos",
    "sexta": "sexta",
    "sexto": "sexto",
    "secao": "se\u00e7\u00e3o",
    "sidra": "sidra",
    "sigam": "sigam",
    "sigla": "sigla",
    "signo": "signo",
    "silos": "silos",
    "sinal": "sinal",
    "sinha": "sinh\u00e1",
    "sinho": "sinh\u00f4",
    "sinos": "sinos",
    "sinta": "sinta",
    "sinto": "sinto",
    "sirva": "sirva",
    "sirvo": "sirvo",
    "sismo": "sismo",
    "situa": "situa",
    "skate": "skate",
    "soara": "soara",
    "soava": "soava",
    "sobem": "sobem",
    "sobra": "sobra",
    "sobre": "sobre",
    "socar": "socar",
    "socos": "socos",
    "sofra": "sofra",
    "sofre": "sofre",
    "sofri": "sofri",
    "sofro": "sofro",
    "sofas": "sof\u00e1s",
    "sogra": "sogra",
    "sogro": "sogro",
    "solar": "solar",
    "solas": "solas",
    "solda": "solda",
    "soldo": "soldo",
    "solta": "solta",
    "solto": "solto",
    "somam": "somam",
    "somar": "somar",
    "somas": "somas",
    "somem": "somem",
    "somos": "somos",
    "sonar": "sonar",
    "sonda": "sonda",
    "sonha": "sonha",
    "sonho": "sonho",
    "sonsa": "sonsa",
    "sopas": "sopas",
    "sopra": "sopra",
    "sopro": "sopro",
    "sorgo": "sorgo",
    "soros": "soros",
    "sorri": "sorri",
    "sorte": "sorte",
    "soube": "soube",
    "suada": "suada",
    "suado": "suado",
    "suave": "suave",
    "subia": "subia",
    "subir": "subir",
    "subiu": "subiu",
    "sucos": "sucos",
    "sueca": "sueca",
    "sueco": "sueco",
    "sufle": "sufl\u00e9",
    "sugam": "sugam",
    "sugar": "sugar",
    "sujar": "sujar",
    "sujas": "sujas",
    "sujos": "sujos",
    "sulco": "sulco",
    "sumia": "sumia",
    "sumir": "sumir",
    "sumiu": "sumiu",
    "sumos": "sumos",
    "sunga": "sunga",
    "super": "super",
    "supor": "supor",
    "supra": "supra",
    "supre": "supre",
    "supos": "sup\u00f4s",
    "supoe": "sup\u00f5e",
    "surda": "surda",
    "surdo": "surdo",
    "surfe": "surfe",
    "surge": "surge",
    "surja": "surja",
    "surra": "surra",
    "surta": "surta",
    "surte": "surte",
    "surto": "surto",
    "sushi": "sushi",
    "susto": "susto",
    "sutil": "sutil",
    "sutis": "sutis",
    "sutia": "suti\u00e3",
    "suina": "su\u00edna",
    "suino": "su\u00edno",
    "suite": "su\u00edte",
    "suica": "su\u00ed\u00e7a",
    "suico": "su\u00ed\u00e7o",
    "sabio": "s\u00e1bio",
    "sepia": "s\u00e9pia",
    "serie": "s\u00e9rie",
    "serio": "s\u00e9rio",
    "semen": "s\u00eamen",
    "simio": "s\u00edmio",
    "sirio": "s\u00edrio",
    "sitio": "s\u00edtio",
    "socia": "s\u00f3cia",
    "socio": "s\u00f3cio",
    "sodio": "s\u00f3dio",
    "sosia": "s\u00f3sia",
    "sotao": "s\u00f3t\u00e3o",
    "taboa": "taboa",
    "tacho": "tacho",
    "tacos": "tacos",
    "talco": "talco",
    "talha": "talha",
    "talho": "talho",
    "talos": "talos",
    "talao": "tal\u00e3o",
    "tampa": "tampa",
    "tampo": "tampo",
    "tanga": "tanga",
    "tange": "tange",
    "tango": "tango",
    "tanta": "tanta",
    "tanto": "tanto",
    "tapar": "tapar",
    "tapas": "tapas",
    "tarda": "tarda",
    "tarde": "tarde",
    "tardo": "tardo",
    "tarja": "tarja",
    "tarso": "tarso",
    "tasca": "tasca",
    "tatua": "tatua",
    "tatus": "tatus",
    "taxar": "taxar",
    "taxas": "taxas",
    "tacas": "ta\u00e7as",
    "tchau": "tchau",
    "tecem": "tecem",
    "tecer": "tecer",
    "teceu": "teceu",
    "tecla": "tecla",
    "teias": "teias",
    "teima": "teima",
    "telas": "telas",
    "telha": "telha",
    "telao": "tel\u00e3o",
    "temas": "temas",
    "temem": "temem",
    "temer": "temer",
    "temia": "temia",
    "temor": "temor",
    "temos": "temos",
    "tempo": "tempo",
    "tenaz": "tenaz",
    "tenda": "tenda",
    "tende": "tende",
    "tendo": "tendo",
    "tenha": "tenha",
    "tenho": "tenho",
    "tenor": "tenor",
    "tenra": "tenra",
    "tenro": "tenro",
    "tensa": "tensa",
    "tenso": "tenso",
    "tenta": "tenta",
    "tente": "tente",
    "tento": "tento",
    "terei": "terei",
    "terem": "terem",
    "teres": "teres",
    "teria": "teria",
    "termo": "termo",
    "terna": "terna",
    "terno": "terno",
    "terra": "terra",
    "teras": "ter\u00e1s",
    "terao": "ter\u00e3o",
    "terca": "ter\u00e7a",
    "terco": "ter\u00e7o",
    "teses": "teses",
    "testa": "testa",
    "teste": "teste",
    "testo": "testo",
    "tesao": "tes\u00e3o",
    "tetas": "tetas",
    "tetos": "tetos",
    "tetra": "tetra",
    "texto": "texto",
    "tidas": "tidas",
    "tidos": "tidos",
    "tiete": "tiete",
    "tigre": "tigre",
    "times": "times",
    "tinge": "tinge",
    "tinha": "tinha",
    "tinta": "tinta",
    "tinto": "tinto",
    "tipos": "tipos",
    "tique": "tique",
    "tiram": "tiram",
    "tirar": "tirar",
    "tiras": "tiras",
    "tirei": "tirei",
    "tirem": "tirem",
    "tiros": "tiros",
    "tirou": "tirou",
    "titio": "titio",
    "tiver": "tiver",
    "tocam": "tocam",
    "tocar": "tocar",
    "tocas": "tocas",
    "tocha": "tocha",
    "tocos": "tocos",
    "tocou": "tocou",
    "todas": "todas",
    "todos": "todos",
    "tolas": "tolas",
    "toldo": "toldo",
    "tolos": "tolos",
    "tomam": "tomam",
    "tomar": "tomar",
    "tomba": "tomba",
    "tombo": "tombo",
    "tomei": "tomei",
    "tomem": "tomem",
    "tomos": "tomos",
    "tomou": "tomou",
    "tonal": "tonal",
    "tonel": "tonel",
    "tonga": "tonga",
    "tonta": "tonta",
    "tonto": "tonto",
    "topou": "topou",
    "toque": "toque",
    "toras": "toras",
    "torce": "torce",
    "torna": "torna",
    "torne": "torne",
    "torno": "torno",
    "torpe": "torpe",
    "torra": "torra",
    "torre": "torre",
    "torta": "torta",
    "torto": "torto",
    "torca": "tor\u00e7a",
    "torco": "tor\u00e7o",
    "tosca": "tosca",
    "tosco": "tosco",
    "tosse": "tosse",
    "tosta": "tosta",
    "total": "total",
    "totem": "totem",
    "touca": "touca",
    "touro": "touro",
    "traga": "traga",
    "trago": "trago",
    "traia": "traia",
    "trair": "trair",
    "traiu": "traiu",
    "traje": "traje",
    "trama": "trama",
    "trapo": "trapo",
    "trara": "trar\u00e1",
    "trata": "trata",
    "trate": "trate",
    "trato": "trato",
    "trava": "trava",
    "trave": "trave",
    "travo": "travo",
    "traze": "traze",
    "traca": "tra\u00e7a",
    "traco": "tra\u00e7o",
    "treco": "treco",
    "trela": "trela",
    "trema": "trema",
    "treme": "treme",
    "tremo": "tremo",
    "trena": "trena",
    "trens": "trens",
    "treno": "tren\u00f3",
    "trepa": "trepa",
    "treta": "treta",
    "treva": "treva",
    "trevo": "trevo",
    "treze": "treze",
    "tribo": "tribo",
    "trico": "tric\u00f4",
    "trigo": "trigo",
    "trina": "trina",
    "trios": "trios",
    "tripa": "tripa",
    "tripe": "trip\u00e9",
    "troca": "troca",
    "troco": "troco",
    "trono": "trono",
    "tropa": "tropa",
    "trote": "trote",
    "trova": "trova",
    "trufa": "trufa",
    "trupe": "trupe",
    "truta": "truta",
    "tubos": "tubos",
    "tufos": "tufos",
    "tufao": "tuf\u00e3o",
    "tumba": "tumba",
    "tumor": "tumor",
    "turbo": "turbo",
    "turca": "turca",
    "turco": "turco",
    "turfa": "turfa",
    "turma": "turma",
    "turno": "turno",
    "turne": "turn\u00ea",
    "turra": "turra",
    "turva": "turva",
    "turvo": "turvo",
    "tutor": "tutor",
    "tabua": "t\u00e1bua",
    "tatil": "t\u00e1til",
    "taxis": "t\u00e1xis",
    "tedio": "t\u00e9dio",
    "tenia": "t\u00eania",
    "tenis": "t\u00eanis",
    "tenue": "t\u00eanue",
    "tibia": "t\u00edbia",
    "torax": "t\u00f3rax",
    "torio": "t\u00f3rio",
    "tonus": "t\u00f4nus",
    "tunel": "t\u00fanel",
    "uivar": "uivar",
    "ultra": "ultra",
    "ungir": "ungir",
    "unhas": "unhas",
    "uniam": "uniam",
    "unida": "unida",
    "unido": "unido",
    "unira": "unira",
    "uniao": "uni\u00e3o",
    "uncao": "un\u00e7\u00e3o",
    "ureia": "ureia",
    "urina": "urina",
    "urnas": "urnas",
    "ursos": "ursos",
    "urubu": "urubu",
    "usada": "usada",
    "usado": "usado",
    "usara": "usara",
    "usava": "usava",
    "usina": "usina",
    "usual": "usual",
    "usura": "usura",
    "vacas": "vacas",
    "vadia": "vadia",
    "vadio": "vadio",
    "vagar": "vagar",
    "vagas": "vagas",
    "vagem": "vagem",
    "vagos": "vagos",
    "vagao": "vag\u00e3o",
    "vaiar": "vaiar",
    "vaias": "vaias",
    "valas": "valas",
    "valem": "valem",
    "valer": "valer",
    "vales": "vales",
    "valeu": "valeu",
    "valha": "valha",
    "valia": "valia",
    "valor": "valor",
    "valsa": "valsa",
    "vamos": "vamos",
    "vapor": "vapor",
    "varal": "varal",
    "varas": "varas",
    "varia": "varia",
    "varre": "varre",
    "varao": "var\u00e3o",
    "vasco": "vasco",
    "vasos": "vasos",
    "vasta": "vasta",
    "vasto": "vasto",
    "vazam": "vazam",
    "vazar": "vazar",
    "vazia": "vazia",
    "vazio": "vazio",
    "vazou": "vazou",
    "vazao": "vaz\u00e3o",
    "veado": "veado",
    "vedar": "vedar",
    "veias": "veias",
    "veios": "veios",
    "vejam": "vejam",
    "velar": "velar",
    "velas": "velas",
    "velha": "velha",
    "velho": "velho",
    "veloz": "veloz",
    "vemos": "vemos",
    "venal": "venal",
    "vence": "vence",
    "venci": "venci",
    "venda": "venda",
    "vende": "vende",
    "vendi": "vendi",
    "vendo": "vendo",
    "venha": "venha",
    "venho": "venho",
    "venta": "venta",
    "vento": "vento",
    "venca": "ven\u00e7a",
    "veras": "veras",
    "verba": "verba",
    "verbo": "verbo",
    "verde": "verde",
    "verem": "verem",
    "veria": "veria",
    "verme": "verme",
    "versa": "versa",
    "verso": "verso",
    "verte": "verte",
    "verve": "verve",
    "verao": "ver\u00e3o",
    "vespa": "vespa",
    "veste": "veste",
    "vesti": "vesti",
    "vetar": "vetar",
    "vetor": "vetor",
    "vetos": "vetos",
    "vetou": "vetou",
    "vezes": "vezes",
    "viaja": "viaja",
    "viaje": "viaje",
    "viajo": "viajo",
    "vibra": "vibra",
    "vicia": "vicia",
    "vidas": "vidas",
    "vidro": "vidro",
    "viela": "viela",
    "viera": "viera",
    "vigas": "vigas",
    "vigia": "vigia",
    "vigor": "vigor",
    "vilas": "vilas",
    "vilao": "vil\u00e3o",
    "vimos": "vimos",
    "vinco": "vinco",
    "vinda": "vinda",
    "vindo": "vindo",
    "vinga": "vinga",
    "vinha": "vinha",
    "vinho": "vinho",
    "vinil": "vinil",
    "vinte": "vinte",
    "viola": "viola",
    "viral": "viral",
    "viram": "viram",
    "virar": "virar",
    "viras": "viras",
    "virei": "virei",
    "virem": "virem",
    "viria": "viria",
    "viril": "viril",
    "viris": "viris",
    "virou": "virou",
    "virao": "vir\u00e3o",
    "visam": "visam",
    "visar": "visar",
    "visor": "visor",
    "visse": "visse",
    "vista": "vista",
    "visto": "visto",
    "visao": "vis\u00e3o",
    "vital": "vital",
    "vitro": "vitro",
    "vivam": "vivam",
    "vivas": "vivas",
    "vivaz": "vivaz",
    "vivem": "vivem",
    "viver": "viver",
    "viveu": "viveu",
    "vivia": "vivia",
    "vivos": "vivos",
    "vizir": "vizir",
    "viuva": "vi\u00fava",
    "viuvo": "vi\u00favo",
    "voara": "voara",
    "vocal": "vocal",
    "voces": "voc\u00eas",
    "vodka": "vodka",
    "vogal": "vogal",
    "volta": "volta",
    "volte": "volte",
    "volto": "volto",
    "voraz": "voraz",
    "vossa": "vossa",
    "vosso": "vosso",
    "votam": "votam",
    "votar": "votar",
    "votos": "votos",
    "votou": "votou",
    "vovos": "vov\u00f3s",
    "vozes": "vozes",
    "vulgo": "vulgo",
    "vulto": "vulto",
    "vulva": "vulva",
    "vacuo": "v\u00e1cuo",
    "venus": "v\u00eanus",
    "vicio": "v\u00edcio",
    "video": "v\u00eddeo",
    "virus": "v\u00edrus",
    "volei": "v\u00f4lei",
    "watts": "watts",
    "xampu": "xampu",
    "xeque": "xeque",
    "xerox": "xerox",
    "xiita": "xiita",
    "xinga": "xinga",
    "xisto": "xisto",
    "xenon": "x\u00e9non",
    "zanga": "zanga",
    "zebra": "zebra",
    "zelam": "zelam",
    "zelar": "zelar",
    "zerar": "zerar",
    "zeros": "zeros",
    "zerou": "zerou",
    "zinco": "zinco",
    "zomba": "zomba",
    "zonas": "zonas",
    "zonza": "zonza",
    "zorra": "zorra",
    "zumbi": "zumbi",
    "ziper": "z\u00edper",
    "abaco": "\u00e1baco",
    "acaro": "\u00e1caro",
    "acida": "\u00e1cida",
    "acido": "\u00e1cido",
    "ageis": "\u00e1geis",
    "aguas": "\u00e1guas",
    "aguia": "\u00e1guia",
    "alamo": "\u00e1lamo",
    "album": "\u00e1lbum",
    "alibi": "\u00e1libi",
    "apice": "\u00e1pice",
    "arabe": "\u00e1rabe",
    "ardua": "\u00e1rdua",
    "arduo": "\u00e1rduo",
    "areas": "\u00e1reas",
    "arias": "\u00e1rias",
    "arida": "\u00e1rida",
    "arido": "\u00e1rido",
    "aries": "\u00e1ries",
    "atomo": "\u00e1tomo",
    "atrio": "\u00e1trio",
    "audio": "\u00e1udio",
    "aurea": "\u00e1urea",
    "aureo": "\u00e1ureo",
    "avida": "\u00e1vida",
    "avido": "\u00e1vido",
    "avila": "\u00e1vila",
    "amago": "\u00e2mago",
    "ambar": "\u00e2mbar",
    "animo": "\u00e2nimo",
    "anodo": "\u00e2nodo",
    "ansia": "\u00e2nsia",
    "ebano": "\u00e9bano",
    "ebrio": "\u00e9brio",
    "eguas": "\u00e9guas",
    "epica": "\u00e9pica",
    "epico": "\u00e9pico",
    "epoca": "\u00e9poca",
    "etica": "\u00e9tica",
    "etico": "\u00e9tico",
    "exito": "\u00eaxito",
    "exodo": "\u00eaxodo",
    "iamos": "\u00edamos",
    "icone": "\u00edcone",
    "idolo": "\u00eddolo",
    "impar": "\u00edmpar",
    "impio": "\u00edmpio",
    "indio": "\u00edndio",
    "obito": "\u00f3bito",
    "obvia": "\u00f3bvia",
    "obvio": "\u00f3bvio",
    "oleos": "\u00f3leos",
    "orfao": "\u00f3rf\u00e3o",
    "orfas": "\u00f3rf\u00e3s",
    "orgao": "\u00f3rg\u00e3o",
    "ossea": "\u00f3ssea",
    "osseo": "\u00f3sseo",
    "otica": "\u00f3tica",
    "otico": "\u00f3tico",
    "otima": "\u00f3tima",
    "otimo": "\u00f3timo",
    "ovulo": "\u00f3vulo",
    "oxido": "\u00f3xido",
    "umero": "\u00famero",
    "umida": "\u00famida",
    "umido": "\u00famido",
    "unica": "\u00fanica",
    "unico": "\u00fanico",
    "urano": "\u00farano",
    "urico": "\u00farico",
    "uteis": "\u00fateis",
    "utero": "\u00fatero"
}

let KEYS = {};  // Maps all key class elements ids to the actual DOM element.

/*
    List with all word class elements and respective letter class elements.
    Each word is an object:
    {
        word: <word class element>,
        letters: [<letter class element>]
    }
*/
let USER_WORDS = [];

const N_WORDS = 6;
const N_LETTERS = 5;

let targetWord = '';  // Word to be guessed by the player.
let currWordIndex = 0; // Index of word being edited, 0 to 5 (6 attempts).
let currLetterIndex = 0;  // Index of letter being edited, 0 to 4 (5 letters).
let userWord = ['', '', '', '', '']; // Current word entered by user.
let finished = false;

let totalGames = 0;
let totalVictories = 0;
let victoriesPerAttempt = [0, 0, 0, 0, 0, 0];

// Selects a new random target word, different from the current one.
const chooseRandomWord = () => {
    let newWord = targetWord;
    while (newWord === targetWord) {
        newWord = Object.keys(WORDS)[
            Math.floor(Math.random() * Object.keys(WORDS).length)];
    }
    targetWord = newWord;
}

// Changes the class of the HTML element of a letter.
const updateLetterClass = (wordIndex, letterIndex, className) => {
    let letter = USER_WORDS[wordIndex].letters[letterIndex];
    letter.className = className;
    if (className.includes("active")) {
        letter.onclick = () => { selectLetter(letterIndex) };
    } else {
        letter.onclick = null;
    }
}

// Selects a letter from the current word to be edited.
const selectLetter = (letterIndex) => {
    updateLetterClass(
        currWordIndex, currLetterIndex, "letter letter-active");
    updateLetterClass(
        currWordIndex, letterIndex, "letter letter-active letter-selected");
    currLetterIndex = letterIndex;
}

// Selects the next letter from the current word to be edited..
const nextLetter = () => {
    if (currLetterIndex < N_LETTERS - 1) selectLetter(currLetterIndex + 1);
}

// Selects the previous letter from the current word to be edited..
const previousLetter = () => {
    if (currLetterIndex > 0) selectLetter(currLetterIndex - 1);
}

const updateLetter = (wordIndex, letterIndex, letter) => {
    USER_WORDS[wordIndex].letters[letterIndex].innerHTML = `<p>${letter}</p>`;
}

// Edits the current letter.
const enterLetter = (letter) => {
    if (finished) return;

    letter = letter.toUpperCase();
    if (/^[A-Z]$/i.test(letter)) {
        const keyEl = KEYS["key-" + letter];
        setTimeout(() => { keyEl.classList.add("key-press"); }, 0.3);
        keyEl.classList.remove("key-press");
        userWord[currLetterIndex] = letter;
        updateUserWord(currLetterIndex);
        nextLetter();
    }
}

// Erases the current letter content.
const eraseLetter = () => {
    if (finished) return;

    if (userWord[currLetterIndex] === '') {
        previousLetter();
    } else {
        userWord[currLetterIndex] = '';
        updateUserWord(currLetterIndex);
    }
}

// Updates the background colors of each letter in the current word.
const updateLettersColors = () => {
    // TODO: add CSS animation for letters class change.

    const accentuatedWord = WORDS[userWord.join('').toLowerCase()];

    for (let i = 0; i < N_LETTERS; i++) {
        const userLetterUpper = userWord[i];
        const userLetter = userLetterUpper.toLowerCase();
        updateLetter(currWordIndex, i, accentuatedWord[i].toUpperCase());

        let className = "letter ";
        let key = KEYS["key-" + userLetterUpper];

        if (userLetter === targetWord[i]) {
            className += "letter-correct";
            key.classList.remove("letter-wrong-position");
            key.classList.add("letter-correct");
        } else if (targetWord.includes(userLetter)) {
            className += "letter-wrong-position";
            if (!key.className.includes("letter")) {
                key.classList.add("letter-wrong-position");
            }
        } else {
            className += "letter-not-present";
            key.classList.add("letter-not-present");
        }

        updateLetterClass(currWordIndex, i, className);
    }
}

// Advances to the next word.
const nextWord = () => {
    updateLettersColors();

    // Changes the next word to the current.
    currWordIndex += 1;
    currLetterIndex = 0;
    for (let i = 0; i < N_LETTERS; i++) {
        let className = "letter letter-active";
        if (i === 0) className += " letter-selected";
        updateLetterClass(currWordIndex, i, className);
    }
}

// Returns the game statistics stored on local storage as a dict.
const getStats = () => {
    const stats = JSON.parse(localStorage.getItem("stats"))
        ?? { totalGames: 0, victoriesPerAttempt: [0, 0, 0, 0, 0, 0] };

    totalGames = stats.totalGames;
    totalVictories = stats.victoriesPerAttempt.reduce((sum, x) => sum + x, 0);
    victoriesPerAttempt = stats.victoriesPerAttempt;

    document.getElementById("total-games").innerText = totalGames;
    const totalPercent = totalGames > 0
        ? Math.floor((totalVictories / totalGames) * 100)
        : 0;
    document.getElementById("total-victories").innerText =
        `${totalVictories} (${totalPercent}%)`;

    for (let i = 0; i < 6; i++) {
        const percent = totalVictories > 0
            ? Math.floor((victoriesPerAttempt[i] / totalVictories) * 100)
            : 0;
        document.getElementById(`attempt-${i + 1}`).innerText = `(${percent}%)`;
        document.getElementById(`bar-${i + 1}`).style.flex = percent;
        document.getElementById(`empty-${i + 1}`).style.flex = 100 - percent;
    }

    return stats;
}

const clearStats = () => {
    localStorage.setItem(
        "stats",
        JSON.stringify(
            { totalGames: 0, victoriesPerAttempt: [0, 0, 0, 0, 0, 0] }));
}

// Saves final result of a game to the statistics in local storage.
const saveResult = (isVictory, nAttempts) => {
    let stats = getStats();
    stats.totalGames += 1;
    if (isVictory) stats.victoriesPerAttempt[nAttempts - 1] += 1;
    localStorage.setItem("stats", JSON.stringify(stats));
}

const defeat = () => {
    closeModals();
    finished = true;
    updateLettersColors();
    setTimeout(() => {
        document.getElementById("final-word-defeat").innerHTML =
            `<p>${WORDS[targetWord].toUpperCase()}</p>`;
        showModal("defeat-modal");
    }, 750);
}

const victory = () => {
    closeModals();
    finished = true;
    updateLettersColors();
    setTimeout(() => {
        document.getElementById("final-word-victory").innerHTML =
            `<p>${WORDS[targetWord].toUpperCase()}</p>`;
        showModal("victory-modal");
    }, 750);
}

const submitWord = () => {
    if (finished) return;

    // TODO: check word ignoring accentuation.
    const word = userWord.join('').toLowerCase();
    if (word.length === N_LETTERS && WORDS.hasOwnProperty(word)) {
        if (word === targetWord) {
            saveResult(true, currWordIndex + 1);
            victory();
        }
        else if (currWordIndex < N_WORDS - 1) {
            nextWord();
        }
        else {
            saveResult(false, currWordIndex + 1);
            defeat();
        }

        userWord = ['', '', '', '', ''];
    } else {
        showModal("invalid-word-modal");
    }
}

// Updates the DOM elements of the current word entered by the user.
const updateUserWord = (letterIndex = null) => {
    const letters = USER_WORDS[currWordIndex].letters;

    if (letterIndex !== null) {
        letters[letterIndex].innerHTML = `<p>${userWord[letterIndex]}</p>`;
    } else {
        for (let i = 0; i < N_LETTERS; i++) {
            letters[i].innerHTML = `<p>${userWord[i]}</p>`;
        }
    }
}

const eraseWord = (wordIndex) => {
    let letters = USER_WORDS[wordIndex].letters;
    for (let i = 0; i < N_LETTERS; i++) {
        letters[i].innerHTML = '<p></p>';
    }
}

const startNewWord = () => {
    // Erases curent words.
    for (let i = 0; i <= currWordIndex; i++)  eraseWord(i);

    chooseRandomWord();
    currLetterIndex = 0;
    currWordIndex = 0;
    userWord = ['', '', '', '', ''];
    updateUserWord();

    // Changes all letters to disabled, first word letters to active and first
    // letter to selected.
    for (let i = 0; i < N_WORDS; i++) {
        for (let j = 0; j < N_LETTERS; j++) {
            let className = "letter";
            if (i === 0) className += " letter-active";
            if (i === 0 && j === 0) className += " letter-selected";
            updateLetterClass(i, j, className);
        }
    }

    // Changes all keys to default class.
    for (const [keyId, keyEl] of Object.entries(KEYS)) {
        if (keyId !== "key-delete" && keyId !== "key-enter") {
            keyEl.className = "key";
        }
    };
}

// Maps keys elements ids to the HTML element.
const __loadKeys = () => {
    let keys = document.getElementsByClassName("key");
    KEYS = {};
    Array.prototype.forEach.call(keys, key => { KEYS[key.id] = key; });
}

// Liists all word elements and respective letter elements.
const __loadWords = () => {
    USER_WORDS = Array.prototype.map.call(
        document.getElementsByClassName("word"),
        (word) => {
            return {
                'word': word,
                'letters': word.getElementsByClassName("letter")
            }
        }
    );
}

// Adds the callbacks for the virtual keyboard (in the page).
const __initializeKeyboard = () => {
    for (const [keyId, keyEl] of Object.entries(KEYS)) {
        const keyName = keyId.split("-")[1];
        if (keyName === "enter") keyEl.onclick = submitWord;
        else if (keyName === "delete") keyEl.onclick = eraseLetter;
        else keyEl.onclick = () => { enterLetter(keyName) };
    }
}

// Adds the callbacks for the physical keyboard.
const __initializeKeyPress = () => {
    document.addEventListener("keypress", (event) => {
        if (event.key === "Enter") submitWord();
        else enterLetter(event.key);
    });

    document.addEventListener("keydown", (event) => {
        if (event.key === "Backspace") eraseLetter();
        else if (event.key === "ArrowLeft") previousLetter();
        else if (event.key === "ArrowRight") nextLetter();
    });
}

window.addEventListener("load", function () {
    __loadKeys();
    __loadWords();

    __initializeKeyboard();
    __initializeKeyPress();

    startNewWord();

    // FIXME: not working. Tested on Android, Chrome and Firefox.
    // Hides the address bar in mobile browsers.
    setTimeout(() => { window.scrollTo(0, 1) }, 0);

    showModal("help-modal");
});

const showModal = (modalId) => {
    const modals = document.getElementsByClassName("modal");
    const words = document.getElementById("words");
    const keyboard = document.getElementById("keyboard");
    words.classList.remove("main-modal-open");
    keyboard.classList.remove("main-modal-open");

    Array.prototype.forEach.call(
        modals,
        (el) => {
            if (el.id === modalId) {
                el.classList.add("modal-open");
                words.classList.add("main-modal-open");
                keyboard.classList.add("main-modal-open");
            } else {
                el.classList.remove("modal-open");
            }
        }
    );
}

const closeModals = () => {
    showModal(null);

    if (finished) {
        finished = false;
        startNewWord();
    }
}
